// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashier.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (id, created_at, updated_at, denomination, quantity)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
) RETURNING id, created_at, updated_at, denomination, quantity
`

type CreateBillParams struct {
	Denomination int32
	Quantity     int32
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill, arg.Denomination, arg.Quantity)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Denomination,
		&i.Quantity,
	)
	return i, err
}

const getBillByDenomination = `-- name: GetBillByDenomination :one
SELECT id, created_at, updated_at, denomination, quantity FROM bills WHERE denomination = $1
`

func (q *Queries) GetBillByDenomination(ctx context.Context, denomination int32) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillByDenomination, denomination)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Denomination,
		&i.Quantity,
	)
	return i, err
}

const getBills = `-- name: GetBills :many
SELECT id, created_at, updated_at, denomination, quantity FROM bills ORDER BY denomination DESC
`

func (q *Queries) GetBills(ctx context.Context) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, getBills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Denomination,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills
SET quantity = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, denomination, quantity
`

type UpdateBillParams struct {
	ID       uuid.UUID
	Quantity int32
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, updateBill, arg.ID, arg.Quantity)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Denomination,
		&i.Quantity,
	)
	return i, err
}
